development:
  adapter: postgresql
  encoding: unicode
  database: valutist_dev
  pool: 8
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: valutist_test
  pool: 8
  username:
  password:
